### ISSUE TITLE
Добавить поддержку переменной окружения API_SERVER_ADDRESS

### ISSUE THREAD

**Issue by wildermesser** [finganapre/MEVN-for-teta-test#2]
Добавить поддержку переменной окружения API_SERVER_ADDRESS для указания адреса сервера приложения

**Comment by finganapre** [comment]
Лучше использовать что-то вроде BASE_URL в качестве имени, так будет логичнее и эту переменную можно будет использовать где-нибудь ещё.

**Comment by wildermesser** [comment]
Да, пожалуй для api будет логичнее, так как могут быть разные endpoints для разных целей
